=== friedmannt/yescomment/YesCommentLogic/ejbModule/crawlerconfigs.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://yescomment.com" xmlns="http://yescomment.com">

  <xs:element name="crawlerconfig" type="crawlerConfig"/>

  <xs:element name="crawlerconfigs" type="crawlerConfigs"/>

  <xs:complexType name="crawlerConfigs">
    <xs:sequence>
      <xs:element ref="crawlerconfig" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="crawlerConfig">
    <xs:sequence/>
    <xs:attribute name="enabled" type="xs:boolean" use="required"/>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="rssUrl" type="xs:string" use="required"/>
    <xs:attribute name="hour" type="xs:int" use="required" />
    <xs:attribute name="minute" type="xs:int" use="required"/>
    <xs:attribute name="delaySec" type="xs:int"/>
  </xs:complexType>
</xs:schema>

=== friedmannt/yescomment/YesCommentLogic/ejbModule/crawlerconfigs.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<crawlerconfigs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="crawlerconfigs.xsd">
    <crawlerconfig enabled="true" name="index" rssUrl="http://index.hu/24ora/rss/"  hour="13" minute="24" delaySec="60"/>
    <crawlerconfig enabled="true" name="portfolio.hu" rssUrl="http://www.portfolio.hu/rss/cikkek/all.xml" hour="13" minute="30"/>
    <crawlerconfig enabled="true" name="velvet" rssUrl="http://velvet.hu/24ora/rss/" hour="15" minute="13" delaySec="30"/>
    <crawlerconfig enabled="true" name="indexvideo" rssUrl="http://index.hu/video/rss/" hour="15" minute="01" delaySec="30"/>
    <crawlerconfig enabled="true" name="origo" rssUrl="http://www.origo.hu/contentpartner/rss/hircentrum/origo.xml" hour="14" minute="58" />
    <crawlerconfig enabled="true" name="hvg" rssUrl="http://hvg.hu/rss" hour="14" minute="55" />
    <crawlerconfig enabled="true" name="nol" rssUrl="http://nol.hu/feed/osszes.rss" hour="13" minute="29" />
    <crawlerconfig enabled="true" name="mno" rssUrl="http://mno.hu/rss" hour="13" minute="42" />
</crawlerconfigs>
